import './globals.css';
import { Global } from '@emotion/react';
import GlobalStyle from '@/styles/reset';
import Providers from '@/components/Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <GlobalStyle />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
